# Build the frontend
FROM node:20-alpine AS frontend

WORKDIR /frontend-build

COPY . .

WORKDIR /frontend-build/

RUN yarn install
RUN yarn build


# Build the backend
FROM golang:1.22-alpine AS backend

WORKDIR /backend-build

RUN go install github.com/cosmtrek/air@latest

COPY . .
# RUN go mod download

# COPY ./cmd ./cmd

CMD ["air", "-c", ".air.toml"]

# Build the final image
FROM alpine:latest AS monolithic

WORKDIR /usr/local/sirichai

RUN apk add --no-cache tzdata
ENV TZ="UTC"

COPY --from=frontend /frontend-build/ /usr/local/sirichai/dist
COPY --from=backend /backend-build /usr/local/sirichai/

EXPOSE 8080