server:
  proxy: https://sirichai-app.onrender.com
  addr: 0.0.0.0
  port: 8080

mongo:
  url: mongodb+srv://sirichai99:KzHRIr2802KPFz0R@cluster0.ltftrf5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  host: localhost
  port: 27017
  database: app
  username: root
  password: P@ssw0rd

assistant:
  url: https://api.dify.ai/v1
  key: app-cje8JxG7HCJMJF1Dt1V0WJpR

secret:
  key: sirichai-44-secret-key
#KzHRIr2802KPFz0R
